### ISSUE TITLE
Feature: User can view cards for sale

### ISSUE THREAD

**Issue by henryrding** [henryrding/final-project#1]
## ⚙️ Feature

User can view cards for sale.

## 📐 Functionality

User can view the pictures, names, and prices of the cards for sale on the home page.

`Home main screen`
-Can view cards for sale and click on them to view detailed information
-Can click on cart icon to view cart
-Can click on sign-in/register button to go to login page
-If logged in, can click sign-out button to go to sign-out confirmation screen
-Can click on profile button to see orders if signed in

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/121365432/232394202-1ee79855-1161-4fe9-91f4-6ad63ab90666.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to have table names, fields, data types, and the relationships between them.
- [x] Update `data.sql` to include dummy data in `inventory` and `users`.

### ☁️ Server Tasks

- [x] Update `server.js` to handle `GET` request to database for list of inventory.
- [x] Test with HTTPie.
- [x] Handle all errors and respond to the client.

### ⚡ Client Tasks

- [x] Create a component to contain app logo and navigation icons with a navigation bar.
- [x] Create a component to show a search bar.
- [x] Create a component to show a single card and its information.
- [x] Create a component to show a list of all single card components.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
