### ISSUE TITLE
Feature: User can checkout

### ISSUE THREAD

**Issue by henryrding** [henryrding/final-project#10]
## ⚙️ Feature

User can checkout.

## 📐 Functionality

User can click the checkout button on the cart screen to go to the checkout page where they can fill in the checkout form. When checkout is successful, they can view a message confirming the order with an order number and that details have been sent to their email. They can also click back to homepage button to go to main screen.

'
`Checkout screen`
-Can view list of items in cart
-Can enter payment and shipping information
-Can click back to cart to go to cart screen
-Can click continue shopping button to go back to main screen for list of cards
-Can click submit order button to submit order

`Order submitted confirmation screen`
-Can view message confirming order with order number and details sent to email
-Can click back to homepage button to go to main screen

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/121365432/232546261-b51746d8-eeb9-49b3-aac0-fbc2241d75b5.png)
![image](https://user-images.githubusercontent.com/121365432/232546320-f56885bd-122d-4dd8-a370-4fe7ed0e79c3.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to include shippingName, shippingAddress, and shippingCost to orders table.

### ☁️ Server Tasks

- [x] Update `server.js` to include stripe and create middleware for checkout.
- [x] Update `server.js` to listen for successful checkout with stripe.
- [x] Update `server.js` to insert new order, insert into orderItems cards in cart, change quantity of inventory, and delete cards in cartInventory on successful checkout.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update `ShopContext` to use database for cartInventory when logged in and localStorage when not logged in.
- [x] Update `Card` and `CardDetails` components to show if a card is out of stock.
- [x] Create `getTotalQuantity` and `handleToast` functions.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
