### ISSUE TITLE
Feature: User can view their orders

### ISSUE THREAD

**Issue by henryrding** [henryrding/final-project#11]
## ⚙️ Feature

User can view their orders.

## 📐 Functionality

User can click on the user icon to view a list of their orders.

`Orders screen`
-Can view list of active/completed orders
-Can click on an order to view details about the selected order
-If there are no active orders, message and button will display to go to main page to buy cards

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/121365432/232546779-6d0adb68-63e7-4727-a81c-7f7df87b95b8.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server.js` to have stripe checkout session include tax.
- [x] Update `server.js` with middleware to get orderItems of a user.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update `api.js` component with `fetchOrderItems` function.
- [x] Update `ShopContext.js` with `orderItems` state and a useEffect that calls `fetchOrderItems` is user is signed in.
- [x] Update `Orders.js` to show all users orders.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
