### ISSUE TITLE
Feature: User can view detailed order information

### ISSUE THREAD

**Issue by henryrding** [henryrding/final-project#12]
## ⚙️ Feature

User can view detailed order information.

## 📐 Functionality

User can click on an order in their orders list to go to the order details page which shows the order number, items ordered, their prices, and the total price.

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/121365432/232547479-57c8a60c-84d7-4aba-8608-3af78625a593.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Update `App.js` component to have route for `orderDetails`
- [x] Update `Orders` component to pass individual order information through `Link`'s `state` attribute to `orderDetails`
- [x] Create `OrderDetails` page component to display details of an order

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
