### ISSUE TITLE
Feature: User can search for cards for sale

### ISSUE THREAD

**Issue by henryrding** [henryrding/final-project#13]
## ⚙️ Feature

User can search for cards for sale.

## 📐 Functionality

User can type in the search bar on the home screen to search through the catalog of cards by name.

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/121365432/232547929-1187204c-650e-4af6-b013-3b1034e63a0b.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Update `Search.js` component to filter inventory based on `searchQuery` state.
- [x] Update `Catalog.js` page component with `searchResults` state and to map `searchResults` instead of `inventory`.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
