### ISSUE TITLE
Feature: User can view inventory of cards for sale (admin)

### ISSUE THREAD

**Issue by henryrding** [henryrding/final-project#14]
## ⚙️ Feature

User can view inventory of cards for sale (admin).

## 📐 Functionality

Admin user can view the cards they have listed for sale and search for them by name.

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/121365432/232553569-1d0bdb42-fc9b-43cc-8fed-41c526bd70cf.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `data.sql` to have an admin account.

### ☁️ Server Tasks

- [x] Update `server.js` to only create a cart for a user if they are not an admin.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update `Card.js` component to also show quantity for admin users. 

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
