### ISSUE TITLE
Feature: User can update inventory of specific cards (admin)

### ISSUE THREAD

**Issue by henryrding** [henryrding/final-project#15]
## ⚙️ Feature

User can update inventory of specific cards (admin).

## 📐 Functionality

Admin user can click a card they have listed to show modal that allows them to change the price and quantity, update the card with the new values, delete the card from their catalog, or close the modal.

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/121365432/232554275-ea411d24-d32c-4ca4-8f50-74afbfbf5c13.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server.js` to patch inventory if admin
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update `api.js` component with updateInventory function
- [x] Update `CardDetails.js` page component to conditionally render inventory update form and toast message if user is admin
- [x] Update `CardDetails.js` page component with `handlePriceChange` and `handleUpdate` functions

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
