### ISSUE TITLE
Feature: User can remove cards from inventory of cards for sale (admin)

### ISSUE THREAD

**Issue by henryrding** [henryrding/final-project#16]
## ⚙️ Feature

User can remove cards from inventory of cards for sale (admin).

## 📐 Functionality

Admin user can click the `delete` button to remove a card from their catalog.

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/121365432/232554373-e370bfb4-11ae-4c75-8d5b-2b3e6ab5dbb0.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server.js` to change visible to false when passed false instead of when quantity is 0
- [x] Update `server.js` to delete from cartInventory when quantity is 0 and when visible is false
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update `api.js` component's updateInventory function to implement visible.
- [x] Update `Card.js` component to show out of stock based on quantity instead of visible.
- [x] Update `CardDetails.js` page component with toggle switch for visible.
- [x] Update `CardDetails.js` page component with handleVisibleChange function for visible toggle switch input onChange.
- [x] Update `CardDetails.js` page component to show NotFound component if user isn't admin and card isn't visible.
- [x] Update `Catalog.js` page component to render Card components only for visible cards if user isn't admin.
- [x] Update `ShopContext.js` component's handleSignIn function to set cart only for non-admins.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
