### ISSUE TITLE
Feature: User can search for cards to sell (admin)

### ISSUE THREAD

**Issue by henryrding** [henryrding/final-project#17]
## ⚙️ Feature

User can search for cards to sell (admin).

## 📐 Functionality

Admin user can click on inventory icon to navigate to the `add inventory` page. They can then search for cards to add to the catalog by name.

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/121365432/232554706-6321c2a0-71ac-42e3-a3a4-42f7cb85c2e4.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to use finish as text instead of foil as boolean
- [x] Update `data.sql` to use finish string instead of foil boolean

### ☁️ Server Tasks

- [x] Update `server.js` to use finish instead of foil
- [x] Update `server.js` to include finish in get specific card middleware
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update `App.js` component to include add-inventory route
- [x] Update `api.js` component with fetchApiResponse function to retrieve card objects from scryfall api
- [x] Update `OrderDetails.js`, `CardDetails.js`, `CartItem.js`, and `Card.js` components to use finish instead of foil
- [x] Update `Search.js` component to call fetchApiResponse if not passed an inventory array
- [x] Update `Search.js` component to only call getResults function 500ms after last user input
- [x] Update `AddInventory.js` page component to show `Search.js` component and cards returned from scryfall api as `Card.js` components

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
