### ISSUE TITLE
Feature: User can add cards for sale (admin)

### ISSUE THREAD

**Issue by henryrding** [henryrding/final-project#18]
## ⚙️ Feature

User can add cards for sale (admin).

## 📐 Functionality

Admin can click a search result to show a card details modal where they can choose a price and quantity for the card and either click the `add` button to add it to their catalog, or the `back` button to hide the modal. On successful add, another modal will show with a message displaying the name and quantity of the card added and also an `OK` button to go back to the search page.

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/121365432/232555022-11c1994b-dc9d-4ab2-b09f-89a7c0d00feb.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server.js` to `post` new card to inventory
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client
- [x] Update `error-middleware.js` to send custom message if card is already in inventory when adding

### ⚡ Client Tasks

- [x] Update `api.js` component to have `addToInventory` function for fetch request to add a card to inventory
- [x] Create `formatApiResults` function to format api results to work with existing code
- [x] Update `Card.js` component with jsx for modal, functions to handle form elements, and states to hold values
- [x] Update modal in `Card.js` component to reset form when modal is closed and to show error and success messages after trying to add card to inventory

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
