### ISSUE TITLE
Feature: User can view detailed information about cards for sale

### ISSUE THREAD

**Issue by henryrding** [henryrding/final-project#2]
## ⚙️ Feature

User can view detailed information about cards for sale.

## 📐 Functionality

After user clicks on a card in the catalog, they will be directed to a new page showing the specific card including details such as name, set, price and also see how many are in stock. They will also see an increment button to increase how many the plan to add to cart, an add to card button, and a back button to navigate back to the catalog.

`Card details screen`
-Can view cards detailed information about card
-Can add card to cart
-Can click button to go back to catalog

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/121365432/232394803-fded44c0-0373-405f-84be-6d0a1800d67e.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to include all card details needed for card details page.
- [x] Update `data.sql` to have values for new card details in dummy data.

### ☁️ Server Tasks

- [x] Update `server.js` to handle `GET` request for specific card
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to view product details.
- [x] Update Card component to have the image Link path to the corresponding product details page.
- [x] Create a function `fetchCard` to fetch a single card with matching cardId.
- [x] Create function to handle line breaks in card text.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
