### ISSUE TITLE
Feature: User can add cards to their cart

### ISSUE THREAD

**Issue by henryrding** [henryrding/final-project#3]
## ⚙️ Feature

User can add cards to their cart.

## 📐 Functionality

User will be able to click `+` button to increase number to add to cart, click the `-` button to decrease number to add to card, and click the` add to cart` button to add the card to the cart. A modal will show after adding an item(s) to cart with text denoting the card name and quantity with buttons to go `back to shop` and `go to cart`.

`Added to cart confirmation (overlay)`
-Shows confirmation modal after adding card to cart
-Can click ok/continue shopping button to hide modal and show card details screen
-Can click checkout/cart button to go to cart screen

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/121365432/232395212-ec8e311d-7fa6-4867-a71f-baaf06fe0d20.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Update `CardDetails` component to add the item(s) to cart on submit
- [x] Create a `ShopContext` component to provide context values of `cartInventory` and other functions.
- [x] Update `App` component to have context provider wrapped around `Routes`.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
