### ISSUE TITLE
Feature: User can view their cart

### ISSUE THREAD

**Issue by henryrding** [henryrding/final-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their cart.

## 📐 Functionality

User will be able to click the cart icon in the top nav bar to view their cart. The page will show the list of items in cart, a button for each card to remove it from the cart, a `continue shopping` button to go back to the catalog, and a `checkout` button to go to the checkout page.

`Cart screen`
-Can view list of cards in cart
-Can click on items in cart to edit quantities/condition of specific cards
-Can click remove from cart button remove specific cards from cart
-Can click continue shopping button to go back to main screen for list of cards
-Can click go to checkout button to go to checkout page.

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/121365432/232396236-555dc93f-8a19-4643-a730-90aea00fdd73.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Update `App` component to have a Cart Route and import Cart component.
- [x] Create a `CartItem` component that creates jsx for a unique card in the cart.
- [x] Create `Cart` component that shows a cart empty message if the cart is empty, or will show a `CartItem` per unique card in the cart.
- [x] Update `Cart` component to include a Cart Summary section with checkout and continue shopping buttons.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
