### ISSUE TITLE
Feature: User can edit card quantities in cart

### ISSUE THREAD

**Issue by henryrding** [henryrding/final-project#5]
## ⚙️ Feature

User can edit cart.

## 📐 Functionality

User can edit card quantities from their cart.

`Edit cart item screen (overlay)`
-Can view detailed information of selected card in cart
-Can edit quantity of selected card in cart
-Can click back/cancel to hide overlay without changing values
-Can click save to update quantity/condition of selected card, then hides modal

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/121365432/232544917-d41472f5-0e35-46fc-935f-c0e96f16b0d0.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Update CartItem component to change quantity of card in cart onChange of the select element dropdown.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
