### ISSUE TITLE
Feature: User can sign up and sign in

### ISSUE THREAD

**Issue by henryrding** [henryrding/final-project#7]
## ⚙️ Feature

User can sign up.
User can sign in.

## 📐 Functionality

On the sign in screen, user can click the `register now` button to navigate to the sign up page, where they can enter in their desired username and password and click the `Register` button to create their account.
User can click on the sign in icon to navigate to the sign in page and enter their username and password to log in.

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/121365432/232548663-3f6821e8-c2bc-4df0-9f30-3a5c1d6fb4fc.png)
![image](https://user-images.githubusercontent.com/121365432/232549329-93577277-2e48-4c6a-ba2e-a0dc201925c7.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `data.sql` to have a dummy account with a working hashed password

### ☁️ Server Tasks

- [x] Update `server.js` to handle post requests for sign-up and sign-in
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update `api.js` component with a `signUpOrIn` function to handle fetch requests of sign-up and sign-in
- [x] Create a `AuthForm` component to handle submit of sign-up/sign-in form
- [x] Create a `AuthPage` component to contain `AuthForm`
- [x] Update `ShopContext` component with handleSignIn function
- [x] Update `NavBar` component to show different `nav-link`s if a user is signed in and if user is an admin
- [x] Update `App.js` with route for sign-up
- [x] Update`App.js` with route for sign-in

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
