### ISSUE TITLE
Feature: User can sign out

### ISSUE THREAD

**Issue by henryrding** [henryrding/final-project#8]
## ⚙️ Feature

User can sign out.

## 📐 Functionality

If the user is signed in, they can click the sign out icon to bring up a confirmation modal. The modal will have a button to hide the modal and stay signed in, and another button to continue with the sign out.

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/121365432/232549420-e67be907-4514-4276-a444-327a1813fdf0.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Update `ShopContext` component with handleSignOut function

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
