### ISSUE TITLE
Feature: User can transfer cart on sign in

### ISSUE THREAD

**Issue by henryrding** [henryrding/final-project#9]
## ⚙️ Feature

User can transfer cart on sign in

## 📐 Functionality

When the user signs in, if they already had items in their cart, the cart tied to their account will be replaced with their previous cart from before sign in.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server.js` to add inventory to cart
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client
- [x] Update `server.js` to get a users cart
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client
- [x] Update `server.js` to update the quantity of a cart in cart
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client
- [x] Update `server.js` to delete a specific card in cart
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client
- [x] Update `server.js` to delete all cards in cart
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update `api.js` component with `fetchCartInventory` function
- [x] Update `api.js` component with `addCartInventory` function
- [x] Update `api.js` component with `updateCartInventory` function
- [x] Update `api.js` component with `deleteCartInventory` function
- [x] Update `api.js` component with `clearCartInventory` function
- [x] Update `ShopContext` component functions to work with database if user is signed in

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
